# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nam Nguyen
tagline:          'A Machine Learning learner'
description:      'I am a self-taught Machine Learning Engineer. I enjoy building projects about Machine Learning.'
url:              https://nnguyen168.github.io/
baseurl:          /
